[package]
name = "rapier_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
# bevy = { version = "0.5", default-features = false }
bevy_rapier3d = { version = "0.10.2", features = [ "parallel", "simd-stable" ]}
# bevy_rapier3d = { path = "../bevy_rapier3d-0.10.2", features = [ "parallel", "simd-stable" ]}
# bevy_rapier3d = { path = "../bevy_rapier3d-0.10.2" }

# [patch.crates-io]
# rapier3d = { path = "../rapier3d-0.9.2", features = [ "parallel", "simd-stable" ]}